#!/usr/bin/env python3
"""Emit peload/win32_ordinals.h: the ordinal-to-name map for the libraries a
plug-in imports by number rather than by name.

Why this is needed at all. An import by ordinal carries no name, so the loader
cannot look it up in the stub table and -- worse on i386, where a stdcall callee
pops its own arguments -- cannot know how many bytes to pop for it either. A
stand-in that pops nothing leaves the caller's stack four bytes off per
argument, and the crash lands somewhere else entirely: Chord Organ imports
gdiplus.dll ordinal 1, and the fault that came out of it was inside a *different*
GDI+ function, thirty-two bytes further down the stack, in the editor rather
than at load.

Ordinals are a stable part of these libraries' ABI -- that is the whole point of
importing by one -- so a table of them is worth checking in. This reads them out
of the export directory of real DLLs. Any set of them will do; Wine's builtins
are the easiest to come by and assign the same numbers deliberately, because an
application that imports oleaut32 by ordinal has to keep working under it.

Cross-checked against what this tree already knew independently: winsock's
ordinal 115 was wired to WSAStartup and 116 to WSACleanup by hand, and
DirectSound's ordinal 1 to DirectSoundCreate, long before this script existed.
All three agree with what it reads.

    python3 tools/gen_ordinals.py [dir ...]

with no argument it looks in the usual places for a system32/syswow64 tree.
"""
import os, struct, sys

OUT = os.path.join(os.path.dirname(__file__), "..", "peload", "win32_ordinals.h")

# The libraries worth carrying. Everything the corpus has been seen to import by
# ordinal, plus the ones whose export tables are famously ordinal-first: shlwapi
# and comctl32 have exports that have no name at all.
DLLS = """
    gdiplus oleaut32 ws2_32 wsock32 odbc32 oledlg dsound shlwapi comctl32
    shell32 ole32 winmm version comdlg32 winspool.drv setupapi snmpapi
    wininet msimg32 imm32 advapi32 user32 gdi32 kernel32
""".split()

SEARCH = [
    "/storage02/manjaro-old/gog-galaxy/drive_c/windows/syswow64",
    "/storage02/manjaro-old/gog-galaxy/drive_c/windows/system32",
    os.path.expanduser("~/.wine/drive_c/windows/syswow64"),
    os.path.expanduser("~/.wine/drive_c/windows/system32"),
    "/usr/lib/wine/i386-windows",
    "/usr/lib/wine/x86_64-windows",
]


def exports(path):
    """(ordinal -> name) out of a PE's export directory."""
    d = open(path, "rb").read()
    if d[:2] != b"MZ":
        return {}
    pe = struct.unpack("<I", d[0x3C:0x40])[0]
    if d[pe:pe + 4] != b"PE\0\0":
        return {}
    magic = struct.unpack("<H", d[pe + 24:pe + 26])[0]
    nsec = struct.unpack("<H", d[pe + 6:pe + 8])[0]
    optsz = struct.unpack("<H", d[pe + 20:pe + 22])[0]
    dd = pe + 24 + (96 if magic == 0x10B else 112)
    erva, esz = struct.unpack("<II", d[dd:dd + 8])
    if not erva:
        return {}
    secs = []
    base = pe + 24 + optsz
    for i in range(nsec):
        s = d[base + 40 * i:base + 40 * (i + 1)]
        vsz, va, rsz, rp = struct.unpack("<IIII", s[8:24])
        secs.append((va, max(vsz, rsz), rp))

    def off(r):
        for va, sz, rp in secs:
            if va <= r < va + sz:
                return rp + (r - va)
        return None

    o = off(erva)
    if o is None:
        return {}
    (_, _, _, _, ord_base, _, nnames, _, names_rva, ords_rva) = \
        struct.unpack("<IIIIIIIIII", d[o:o + 40])
    no, oo = off(names_rva), off(ords_rva)
    if no is None or oo is None:
        return {}
    out = {}
    for i in range(nnames):
        nr = struct.unpack("<I", d[no + 4 * i:no + 4 * i + 4])[0]
        nofs = off(nr)
        if nofs is None:
            continue
        name = d[nofs:d.index(b"\0", nofs)].decode("latin1")
        idx = struct.unpack("<H", d[oo + 2 * i:oo + 2 * i + 2])[0]
        out[idx + ord_base] = name
    return out


def main():
    dirs = sys.argv[1:] or [d for d in SEARCH if os.path.isdir(d)]
    if not dirs:
        sys.exit("no directory of Windows DLLs found; pass one on the command line")
    table = []
    seen = {}
    for dll in DLLS:
        fname = dll if dll.endswith(".drv") else dll + ".dll"
        for d in dirs:
            p = os.path.join(d, fname)
            if not os.path.isfile(p):
                continue
            e = exports(p)
            if not e:
                continue
            seen[dll] = (os.path.relpath(p, "/"), len(e))
            for ordinal, name in sorted(e.items()):
                table.append((fname.lower(), ordinal, name))
            break
    if not table:
        sys.exit("found no export tables in %s" % ", ".join(dirs))

    table.sort(key=lambda r: (r[0], r[1]))
    with open(OUT, "w") as f:
        f.write("/* Generated by tools/gen_ordinals.py -- do not edit.\n"
                " *\n"
                " * (dll, ordinal) -> exported name, so an import or a\n"
                " * GetProcAddress by number can be answered by the same stub\n"
                " * table a name goes through, and -- on i386 -- with a stub that\n"
                " * pops the right number of argument bytes.\n"
                " *\n"
                " * Read out of the export directories of:\n")
        for dll in DLLS:
            if dll in seen:
                f.write(" *   %-16s %5d exports\n" % (dll, seen[dll][1]))
        f.write(" */\n"
                "#ifndef PELOAD_WIN32_ORDINALS_H\n"
                "#define PELOAD_WIN32_ORDINALS_H\n\n"
                "typedef struct { const char *dll; unsigned short ord; const char *name; } win32_ordinal;\n\n"
                "/* sorted by dll then ordinal, for a binary search */\n"
                "static const win32_ordinal g_win32_ordinals[] = {\n")
        for dll, ordinal, name in table:
            f.write('    { "%s", %d, "%s" },\n' % (dll, ordinal, name))
        f.write("};\n\n"
                "#define NWIN32ORDINAL ((int)(sizeof g_win32_ordinals / sizeof *g_win32_ordinals))\n\n")
        f.write('''/* The exported name for one ordinal, or NULL.
 *
 * `dll` is taken as it appears in an import descriptor: any case, with or
 * without a directory in front of it, with or without the ".dll" the table
 * stores. */
static const char *win32_ordinal_name(const char *dll, unsigned ordinal)
{
    char key[40];
    const char *p;
    size_t i, n;
    int lo = 0, hi = NWIN32ORDINAL - 1;

    if (!dll || !*dll || ordinal > 0xFFFF) return 0;
    p = dll;
    for (i = 0; dll[i]; i++)
        if (dll[i] == '\\\\' || dll[i] == '/') p = dll + i + 1;
    for (n = 0; p[n] && n + 1 < sizeof key; n++)
        key[n] = (char)((p[n] >= 'A' && p[n] <= 'Z') ? p[n] - 'A' + 'a' : p[n]);
    key[n] = 0;
    /* ".drv" is a real suffix in this table; only ".dll" may be missing. */
    if (n < 4 || (strcmp(key + n - 4, ".dll") && strcmp(key + n - 4, ".drv"))) {
        if (n + 4 < sizeof key) { memcpy(key + n, ".dll", 5); n += 4; }
    }

    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int c = strcmp(g_win32_ordinals[mid].dll, key);
        if (!c) c = (g_win32_ordinals[mid].ord > ordinal) -
                    (g_win32_ordinals[mid].ord < ordinal);
        if (c < 0) lo = mid + 1;
        else if (c > 0) hi = mid - 1;
        else return g_win32_ordinals[mid].name;
    }
    return 0;
}

#endif /* PELOAD_WIN32_ORDINALS_H */
''')
    print("wrote %s: %d ordinals across %d libraries"
          % (os.path.normpath(OUT), len(table), len(seen)))
    for dll in DLLS:
        if dll not in seen:
            print("  (no %s found -- its ordinals are not in the table)" % dll)


if __name__ == "__main__":
    main()
