<#
Generate a registration fragment from Scan-MigDefinitions.ps1 output.
The generated handlers are explicit stubs and never pretend to implement
Darwin semantics; each routine returns an empty reply until implemented.
Wintosh original tooling: MIT; upstream definitions remain upstream-owned.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$InventoryCsv,
    [Parameter(Mandatory=$true)][string]$OutputCpp
)
$rows = @(Import-Csv -LiteralPath $InventoryCsv)
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by Generate-MigRegistry.ps1; stubs require semantic implementation.')
$lines.Add('#include "darling_windows_mig.h"')
$lines.Add('namespace darling::windows_host {')
$lines.Add('void RegisterGeneratedMigStubs(MigRoutineRegistry& registry) {')
$id = 0x2000
foreach ($row in $rows) {
    foreach ($routine in ($row.Routines -split ';' | Where-Object { $_ })) {
        $escaped = $routine -replace '[^A-Za-z0-9_]', '_'
        $lines.Add(('    // {0}: {1}' -f $row.RelativePath, $routine))
        $lines.Add(('    registry.Register({{ {0}, 0, 1048576, 1048576, [](std::span<const std::uint8_t>) {{ return std::vector<std::uint8_t>{{}}; }} }});' -f $id))
        $id++
    }
}
$lines.Add('}')
$lines.Add('}')
$parent = Split-Path -Parent $OutputCpp
if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
$resolvedOutput = [IO.Path]::GetFullPath($OutputCpp)
[IO.File]::WriteAllLines($resolvedOutput, $lines)
Write-Output ("GENERATED_MIG_STUBS={0}" -f ($id - 0x2000))
